version: "3.9"
services:
  notary:
    image: "notary"
    ports:
      - "127.0.0.1:9005:9005"
    environment:
      NOTARY_SLEEP: "5"
    depends_on:
      - "ceresdb"
    tty: true
  ceresdb:
    image: "jfcarter2358/ceresdb:1.1.2"
    ports:
      - "127.0.0.1:7437:7437"
    environment:
      CERESDB_LOG_LEVEL: "trace"
    tty: true